# .github/workflows/order-service-ci.yaml
name: Order Service Pipeline

on:
  push:
    branches: [main]
    paths: ["services/order-service/**", "packages/**", "pnpm-lock.yaml"]

permissions:
  contents: read
  security-events: write
  actions: read    

jobs:
  call-ci:
    uses: ./.github/workflows/reusable-node-ci.yaml
    with:
      service_name: order-service
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}