name: Generic Node CI

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.30.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Docker image
        run: |
          docker build --build-arg SERVICE_NAME=${{ inputs.service_name }} -t skymonil/${{ inputs.service_name }}:${{ github.sha }} -f docker/node-service.Dockerfile . 

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push skymonil/${{ inputs.service_name }}:${{ github.sha }}
      
      - name: Upload Image Digest Artifact
        uses: actions/upload-artifact@v4 # ✅ MUST BE v4
        with:
          name: ${{ inputs.service_name }}-digest
          path: image-digest.txt
