# .github/workflows/reusable-gitops-cd.yaml
name: Generic GitOps CD

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      overlay:
        required: false
        type: string
        default: dev

    secrets:
      GITOPS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: skymonil/event-microservice-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update Helm image tag
        working-directory: gitops
        run: |
          yq -i '.microservice.image.tag = "${{ github.sha }}"' workloads/${{ inputs.overlay }}/${{ inputs.service_name }}/values.yaml

      - name: Commit & push
        working-directory: gitops
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git add workloads/${{ inputs.overlay }}/${{ inputs.service_name }}/values.yaml
          
          git commit -m "Deploy ${{ inputs.service_name }} to ${{ inputs.overlay }} (${{ github.sha }})" || echo "No changes to commit"
          git pull --rebase origin main
          git push 
