name: Generic GitOps CD

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      overlay:
        required: false
        type: string
        default: dev

    secrets:
      GITOPS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: skymonil/event-microservice-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag
        working-directory: gitops/services/${{ inputs.service_name }}/overlays/${{ inputs.overlay }}
        run: |

          IMAGE=skymonil/${{ inputs.service_name }}:${{ github.sha }}

          echo "Updating image to $IMAGE"

          kustomize edit set image \
          skymonil/${{ inputs.service_name }}=$IMAGE


      - name: Commit & push
        run: |

          cd gitops

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git commit -m "Deploy ${{ inputs.service_name }}:${{ github.sha }} to ${{ inputs.overlay }}" || true

          git push