name: User Service Pipeline

on:
  push:
    branches: [main]
    paths: ["services/user-service/**", "packages/**", "pnpm-lock.yaml"]

jobs:
  call-ci:
    uses: ./.github/workflows/reusable-node-ci.yaml
    with:
      service_name: user-service
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}